CREATE DATABASE QuanLyGara
USE QuanLyGara
GO

CREATE TABLE KHACHHANG (
   MAKH					INT IDENTITY(1,1),
   TENKH                NVARCHAR(30),
   DIACHI               NVARCHAR(50),
   DIENTHOAI            VARCHAR(15),
   EMAIL                VARCHAR(30),
   CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)
GO

CREATE TABLE XE (
   BIENSO               VARCHAR(20),
   MAKH                 INT,
   HIEUXE               NVARCHAR(20),
   CONSTRAINT PK_XE PRIMARY KEY (BIENSO),
   CONSTRAINT FK_XE_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
GO

CREATE TABLE PHIEUNHAN (
   MAPHIEUNHAN          INT IDENTITY(1,1),
   BIENSO               VARCHAR(20),
   NGAYNHAN             DATETIME,
   CONSTRAINT PK_PHIEUNHAN PRIMARY KEY (MAPHIEUNHAN),
   CONSTRAINT FK_PHIEUNHAN_XE FOREIGN KEY (BIENSO) REFERENCES XE(BIENSO)
)
GO

CREATE TABLE PHUTUNG (
   MAPHUTUNG            VARCHAR(10),
   TENPHUTUNG           NVARCHAR(50),
   DONGIA               INT,
   SLTON				INT,
   CONSTRAINT PK_PHUTUNG PRIMARY KEY (MAPHUTUNG)
)

GO

CREATE TABLE CONGVIEC (
   MACONGVIEC           VARCHAR(10),
   NOIDUNG              NVARCHAR(60),
   TIENCONG             INT,
   CONSTRAINT PK_CONGVIEC PRIMARY KEY (MACONGVIEC)
)
GO

CREATE TABLE PHIEUSUACHUA (
   MAPHIEUSUA           INT IDENTITY(1,1),
   BIENSO               VARCHAR(20),
   NGAYSUA              DATETIME,
   TINHTRANG            NVARCHAR(20),
   CONSTRAINT PK_PHIEUSUACHUA PRIMARY KEY (MAPHIEUSUA),
   CONSTRAINT FK_PHIEUSUACHUA_XE FOREIGN KEY (BIENSO) REFERENCES XE(BIENSO),
)
GO

CREATE TABLE PHIEUTHU (
   MAPHIEUTHU           INT,
   MAPHIEUSUA           INT,
   NGAYTHU              DATETIME,
   TIENTHU              INT,
   CONSTRAINT PK_PHIEUTHU PRIMARY KEY (MAPHIEUTHU),
   CONSTRAINT FK_PHIEUTHU_PHIEUSUACHUA FOREIGN KEY (MAPHIEUSUA) REFERENCES PHIEUSUACHUA(MAPHIEUSUA)
)
GO

CREATE TABLE CT_PHIEUSUA (
   MAPHIEUSUA           INT,
   MAPHUTUNG            VARCHAR(10),
   MACONGVIEC           VARCHAR(10),
   SL_PHUTUNG           INT,
   CONSTRAINT PK_CT_PHIEUSUA PRIMARY KEY (MAPHIEUSUA, MAPHUTUNG, MACONGVIEC),
   CONSTRAINT FK_CT_PHIEUSUA_PHIEUSUA FOREIGN KEY (MAPHIEUSUA) REFERENCES PHIEUSUACHUA(MAPHIEUSUA),
   CONSTRAINT FK_CT_PHIEUSUA_PHUTUNG FOREIGN KEY (MAPHUTUNG) REFERENCES  PHUTUNG(MAPHUTUNG),
   CONSTRAINT FK_CT_PHIEUSUA_CONGVIEC FOREIGN KEY (MACONGVIEC) REFERENCES CONGVIEC(MACONGVIEC)
)
GO

