--Insert dữ liệu có dấu cần thêm N phía trước chuỗi
--Insert dữ liệu khách hàng
INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Văn A', N'123 Lê Đức Thọ', '0902456789', 'nguyenvana@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Lê Hoài Vũ', N'130 Kha Vạn Cân', '0902456123', 'lehoaivu@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Minh Huy', N'12 Võ Văn Ngân', '0942456789', 'nguyenvanhuy@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Văn Tuấn', N'19 Lê Văn Việt', '0982456789', 'nguyenvantuan@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Lê Thị Tố Quyên', N'121 Lý Thái Tổ', '0942123789', 'lethitoquyen@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Trung Hiếu', N'256 Quang Trung ', '0902456789', 'nguyentrunghieu@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Phan Anh Khoa', N'195 Nguyễn Thái Sơn', '0901231000', 'phananhkhoa@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Phạm Thế Hữu', N'150 Nguyễn Kiệm', '01232199221', 'phamthehuu@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Lê Hoài Nam', N'255 Nguyễn Đình Chiểu', '01632238698', 'lehoainam@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Nhật Thuận', N'232 Điện Biên Phủ', '0902486799', 'nguyennhatthuan@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Văn Hoàng', N'323 Võ Văn Kiệt', '0902358779', 'nguyenvanhoang@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Tiến Quang', N'1256 Điện Biên Phủ', '0902256989', 'nguyentienquan@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Thi Tuong Vi', N'129 Võ Thị Sáu', '0989956779', 'nguyenthituongvi@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Lê Thanh Đạt', N'05 Nguyễn Xí', '0903336726', 'lethanhdat@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Anh Hào', N'325 Đinh Bộ Lĩnh', '0949966679', 'nguyenanhhao@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Lý Đức Chính', N'Biên Hòa, Đồng Nai', '0123776889', 'lyducchinh@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Võ Phạm Việt', N'KTX Khu B DHQG', '01682235623', 'vophamviet@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Kim Khôi', N'Dĩ An, Bình Dương', '0981006779', 'nguyenkimkhoi@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Công Phượng', N'189 Nguyễn Văn Linh', '0902555799', 'nguyencongphuong@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Phan Thành', N'246 Nguyễn Thị Minh Khai', '0909996999', 'phanthanh@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Nguyễn Quốc Cường', N'TP Pleiku, Gia Lai', '0123456789', 'nguyenquoccuong@gmail.com')

INSERT INTO KHACHHANG (TENKH, DIACHI, DIENTHOAI, EMAIL)
VALUES (N'Phạm Trần Nhật Minh', N'134 Nam Kỳ Khởi Nghĩa', '0907756777', 'phamtrannhatminh@gmail.com')
--Insert dữ liệu xe
INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('59G1 9999', 1, 'Toyota')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('60F1 34820', 2, 'Audi')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('81H1 7777', 3, 'Ferrari')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('52B9 9999', 4, 'Lexus')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('53H1 7695', 5, 'Toyota')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('55G1 1234', 6, 'Ford')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('52G1 31455', 7, 'Subaru')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('93F1 7895', 8, 'BMW')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('51L1 42378', 9, 'Mitsubisi')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('59G1 1568', 10, 'Chevrolet')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('52H1 3452', 11, 'Volkswagen')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('56V1 2399', 12, 'Porsche')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('61G1 5699', 13, 'Bentley')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('54G1 9899', 14, 'Ford')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('56F1 7799', 15, 'Toyota')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('66E1 33401', 16, 'Honda')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('65M1 9914', 17, 'Audi')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('93X1 9569', 18, 'BMW')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('29P1 1234', 19, 'McLaren')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('72G1 8888', 20, 'Toyota')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('56L1 4568', 21, 'Mercedes Benz')

INSERT INTO dbo.XE (BIENSO, MAKH, HIEUXE ) VALUES ('59L1 9485', 22, 'Mercedes Benz')






--Insert dữ liệu phụ tùng 
--Thêm cột số lượng
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT001', N'Lọc gió', 1200000, 100)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT002', N'Lọc nhiên liệu', 171000, 50)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT003', N'Phuộc trước toyota innova', 1200000, 75)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT004', N'Máy phát điện toyota innova', 7300000, 20)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT005', N'Lốc lạnh toyota innova tháo xe', 4500000, 30)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT006', N'Mâm ép toyota innova chính hãng', 200000, 80)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT007', N'Bố thắng trước innova chính hãng', 130000, 40)

INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT008', N'Đuôi cá HONDA CIVIC', 2200000, 10)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT009', N'Sét gạt mưa HONDA CIVIC 2.0i size 26″X22″', 460000, 20)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT011', N'Lọc gió động cơ Honda Civic 1.8', 2600000, 10)

INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT012', N'Láp ngang cầu sau', 7100000, 100)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT013', N'Láp dọc đồng bộ', 20500000, 10)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT014', N'Cao su chân máy trước', 900000, 20)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT015', N'Mêm ép', 6900000, 20)
INSERT INTO PHUTUNG (MAPHUTUNG, TENPHUTUNG, DONGIA, SLTON) VALUES ('PT016', N'Búp sen thắng sau', 700000, 30)



--Insert dữ liệu công việc
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV001', N'Công thay dầu máy', 50000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV002', N'Công thay lọc dầu', 50000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV003', N'Công thay lọc dầu', 50000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV004', N'Công ép bi', 80000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV005', N'Công thay thế tháo lắp phụ tùng', 200000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV006', N'Bi lốc điều hòa', 250000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV007', N'Dầu tổng hợp toàn phần idemisu', 300000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV008', N'Lọc dầu giấy', 220000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV009', N'Vệ sinh,làm sạch bảo dưỡng máy', 600000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV010', N'Nắp bình nước phụ', 2500000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV011', N'Đánh bóng cả xe + phủ polyme + tẩy mốc kính', 2000000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV012', N'Gò nắn+ sơn cửa trước phải', 900000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV013', N'Sơn cửa sau trái', 900000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV014', N'Sơn ba bu lê phải', 500000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV015', N'Sơn vá hông phải', 400000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV016', N'Gò nắn sườn hông phải', 300000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV017', N'Gò nắn ba bu lê phải', 200000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV018', N'Gò nắn cửa sau phải', 300000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV019', N'Sơn cửa sau phải ( sơn vào mép trong cánh cửa xe)', 1100000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV020', N'Dầu hộp số tự động', 200000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV021', N'Làm sạch bề mặt', 300000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV022', N'Dầu phanh DOT 3', 150000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV023', N'Giặt phơi nội thất', 1500000)
INSERT INTO CONGVIEC (MACONGVIEC, NOIDUNG, TIENCONG) VALUES ('CV024', N'Xi lanh phanh sau', 420000)





















 


